import { Analytics } from '@vercel/analytics/next'
import type { Metadata, Viewport } from 'next'
import { Inter, Montserrat } from 'next/font/google'
import './globals.css'
import { CookieConsent } from '@/components/site/cookie-consent'
import { MobileActionBar } from '@/components/site/mobile-action-bar'
import { StructuredData } from '@/components/site/structured-data'
import { DESCRIPTION, LEGAL_NAME, SITE_NAME, SITE_URL, TAGLINE } from '@/lib/site'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
  weight: ['600', '700', '800'],
  display: 'swap',
})

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: `${SITE_NAME} | ${TAGLINE} Philippines`,
    template: `%s | ${SITE_NAME}`,
  },
  description: DESCRIPTION,
  applicationName: SITE_NAME,
  // Google ignores meta keywords for ranking; kept short for other engines
  keywords: [
    'Industrial Electronics Repair Philippines',
    'PCB Repair Philippines',
    'Board Repair Philippines',
    'Automation Engineering Philippines',
    'Custom Machine Fabrication',
    'Jigs and Fixtures Fabrication',
    'Metal Fabrication Philippines',
    'Industrial Construction Philippines',
    'Pre-Engineered Buildings',
    'MEPF Contractor Philippines',
    'Engineering Company Cavite',
  ],
  authors: [{ name: LEGAL_NAME }],
  creator: LEGAL_NAME,
  publisher: LEGAL_NAME,
  alternates: { canonical: '/' },
  openGraph: {
    type: 'website',
    locale: 'en_PH',
    url: '/',
    siteName: SITE_NAME,
    title: `${SITE_NAME} | ${TAGLINE}`,
    description: DESCRIPTION,
    // image: generated by app/opengraph-image.tsx (added automatically)
  },
  twitter: {
    card: 'summary_large_image',
    title: `${SITE_NAME} | ${TAGLINE}`,
    description: DESCRIPTION,
  },
  robots: { index: true, follow: true },
  formatDetection: { telephone: false }, // phones are already proper tel: links
}

export const viewport: Viewport = {
  themeColor: '#13203b',
  colorScheme: 'light',
  width: 'device-width',
  initialScale: 1,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${montserrat.variable} bg-background`}>
      <body className="font-sans antialiased">
        <StructuredData />
        {children}
        <MobileActionBar />
        <CookieConsent />
        {process.env.NODE_ENV === 'production' && <Analytics />}
      </body>
    </html>
  )
}
