import { ImageResponse } from 'next/og'
import { FOUNDED, LEGAL_NAME, TAGLINE } from '@/lib/site'

// The preview image shown when the site link is shared (Facebook, LinkedIn,
// Messenger, Viber, Slack…). Generated by Next.js at build time. No design
// file needed. Next wires it into the <meta og:image> tags automatically.
export const alt = `${LEGAL_NAME}: ${TAGLINE}`
export const size = { width: 1200, height: 630 }
export const contentType = 'image/png'

const NAVY = '#13203b'
const ORANGE = '#f58220'

export default function OpengraphImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'space-between',
          padding: '72px 80px',
          background: `linear-gradient(135deg, ${NAVY} 0%, #1d3160 100%)`,
          color: 'white',
          fontFamily: 'sans-serif',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: 18 }}>
          <div
            style={{
              display: 'flex',
              width: 64,
              height: 64,
              borderRadius: 16,
              background: ORANGE,
              alignItems: 'center',
              justifyContent: 'center',
              fontSize: 26,
              fontWeight: 800,
            }}
          >
            PB
          </div>
          <div style={{ display: 'flex', flexDirection: 'column' }}>
            <div style={{ fontSize: 34, fontWeight: 800, letterSpacing: 1 }}>PBTS</div>
            <div style={{ fontSize: 16, letterSpacing: 6, opacity: 0.6 }}>TECHNOLOGY</div>
          </div>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
          <div style={{ fontSize: 68, fontWeight: 800, lineHeight: 1.08 }}>Industrial Engineering,</div>
          <div style={{ fontSize: 68, fontWeight: 800, lineHeight: 1.08 }}>Automation &amp;</div>
          <div style={{ fontSize: 68, fontWeight: 800, lineHeight: 1.08, color: ORANGE }}>Construction.</div>
        </div>

        <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 24, opacity: 0.75 }}>
          <div>{LEGAL_NAME}</div>
          <div>{`Since ${FOUNDED} · Cavite · Bataan · Cebu`}</div>
        </div>
      </div>
    ),
    size,
  )
}
